
project_id = "mufcmhgxskkwggtwryol"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://id-preview--c2e7601d-ec4a-4421-aacc-e1f9be1de1f2.lovable.app", "http://localhost:3000/invite/verify"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.create-brokerage-owner]
verify_jwt = false

[functions.getFormLink]
verify_jwt = true

[studio]
enabled = true
port = 54323
